name: auto tag first characters of the commit sha1

on:
  #push:
  #  branches:
  #    - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Git
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Get commit SHA
        id: get_sha
        run: echo "SHA=$(echo $GITHUB_SHA | cut -c1-4)" >> $GITHUB_ENV

      - name: Create tag
        run: git tag $SHA && git push origin $SHA
